### PR TITLE
Support for executing migrations

### PR DESCRIPTION
**Pull request by ehsanYazdani**
I have created this PR in an attempt to merge the repo https://github.com/exitxhu/EntityFrameworkCore.ClickHouse with this repo from a migrations point of view. While running the code in this PR, I have successfully been able to execute migrations created with this repo.

Unfortunately I was not able to cherry pick the changes from the repo https://github.com/exitxhu/EntityFrameworkCore.ClickHouse to keep the original author's commit as they contain other parts of the library which I did not want to include. In addition, I have cleaned up the code according to the standards of this repo.

### CODE REVIEW

**Comment by denis-ivanov** [comment]
Looks good, but your pr does not contain unit tests, I will investigate it.

**Comment by ehsanYazdani** [comment]
Thanks for the quick response. I did check but the original repo does not contain any either, which is sad. I do believe testa are important and I'm happy to help if you wish, but you may be a better person to write them and it might help give you better insight into the proposed code before it is merged.

**Comment by denis-ivanov** [comment]
Sure, give me some time

**Comment by denis-ivanov** [comment]
@ehsanYazdani, I added ClickHouseHistoryRepository implementation, ClickHouseMigrator is full copy of original Migrator.

Please, try out new version and give feedback.

**Comment by ehsanYazdani** [comment]
I have just tried out the latest release. I have not run any extensive tests, but the simple cases seem to work as expected. Well done. Thank you! 
I assume you want me to close this PR without any further action?

**Comment by denis-ivanov** [comment]
Yes, please close this PR

**Pull request closed without merging**
